version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "metropolitan"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1u8iz7pasjof0"
s3_prefix = "metropolitan"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"Prod\""
