AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  metropolitan

  Sample SAM Template for metropolitan

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  TableName:
    Type: String
    Default: 'simple_metroplitan'
    Description: (Required) The name of the new DynamoDB to store connection identifiers for each connected clients. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z_]+$
    ConstraintDescription: 'Required. Can be characters and underscore only. No numbers or special characters allowed.'

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
  TicktesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: projectId
        AttributeType: S
      - AttributeName: ticketId
        AttributeType: S
      - AttributeName: currentPosition
        AttributeType: S
      KeySchema:
      - AttributeName: projectId
        KeyType: HASH
      - AttributeName: ticketId
        KeyType: RANGE
      LocalSecondaryIndexes:
      - IndexName: currentPositionIndex
        KeySchema:
          - AttributeName: projectId
            KeyType: HASH
          - AttributeName: currentPosition
            KeyType: RANGE
        Projection:
          ProjectionType: KEYS_ONLY
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: True
      TableName: !Ref TableName
  TicketsWebSocket:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: TicketsWebSocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"
Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  TicktesTableArn:
    Description: "Ticktes table ARN"
    Value: !GetAtt TicktesTable.Arn
